[package]
name = "honeycomb"
version = "0.1.0"
authors = ["Adam McDaniel <adam.mcdanie17@gmail.com>"]
edition = "2018"
description = "A portable parser combinator library that does not require a runtime"
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/adam-mcdaniel/honeycomb"
homepage = "https://github.com/adam-mcdaniel/honeycomb"
documentation = "https://docs.rs/honeycomb"

[lib]
doctest = false

[dependencies]